header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: jf-011101

  paths:
    - '**/*.go'
    - '**/*.s'
    - '**/*.thrift'

  paths-ignore:
    - '**/grpc_gen/**'
    - '**/*.proto'

  comment: on-failure