Global:
  Source: "config(local)"
  ChangeMe: "v3"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

TLS:
  Name: "dytt-ca"
  CertFileLocalAddr: "../../config/cert/comment/dytt-comment.pem"
  KeyFileLocalAddr: "../../config/cert/comment/dytt-comment-key.pem"

ZIPKIN:
  SrvName: "dytt-comment-srv"
  CliName: "dytt-comment-cli"
  Url: "http://localhost:9411/api/v2/spans"
  Port: "127.0.0.1:8086"
Server:
  Name: "TiktokCommentServer"
  Address: "127.0.0.1"
  Port: 8086

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"