Global:
  Source: "config(local)"
  ChangeMe: "v3"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

TLS:
  Name: "dytt-ca"
  CertFileLocalAddr: "/home/going/workspace/golang/src/github.com/jf-011101/DYTT/config/cert/feed/dytt-feed.pem"
  KeyFileLocalAddr: "/home/going/workspace/golang/src/github.com/jf-011101/DYTT/config/cert/feed/dytt-feed-key.pem"

ZIPKIN:
  Name: "dytt-feed-srv"
  endpoint: "127.0.0.1:9411"

Server:
  Name: "TiktokFeedServer"
  Address: "127.0.0.1"
  Port: 8083

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

MySQL:
  Host: "127.0.0.1"
  Port: 8091
  User: "tiktok"
  Password: "password"
  DBName: "Tiktok"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"