Global:
  Source: "config(local)"
  ChangeMe: "v3"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

TLS:
  Name: "dytt-ca"
  CertFileLocalAddr: "/home/going/workspace/golang/src/github.com/jf-011101/dytt/config/cert/relation/dytt-relation.pem"
  KeyFileLocalAddr: "/home/going/workspace/golang/src/github.com/jf-011101/dytt/config/cert/relation/dytt-relation-key.pem"

ZIPKIN:
  SrvName: "dytt-relation-srv"
  CliName: "dytt-relation-cli"
  Url: "http://localhost:9411/api/v2/spans"
  Port: "127.0.0.1:8087"
Server:
  Name: "TiktokRelationServer"
  Address: "127.0.0.1"
  Port: 8087

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"