Global:
  Source: "config(local)"
  ChangeMe: "v3"

JWT:
  signingKey: "signingKey"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

Server:
  Name: "TiktokRelationServer"
  Address: "127.0.0.1"
  Port: 8087

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"